**Importing Packages**

In [27]:
from tensorflow.keras.datasets import mnist
from tensorflow import keras
from tensorflow.keras import models,layers
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing import image
import numpy as np
import tensorflow
from tensorflow.keras.callbacks import ModelCheckpoint

**CALL BACK FUNCTION**

In [10]:
class myCallbacks(tensorflow.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs={}):
    if(logs.get('accuracy') > 0.99):
      print('\nDesired Accuracy is Reached!!')
      # self.model.stop.training= True
      self.model.stop_training = True


callback = myCallbacks()

**Loading Mnist Dataset**

In [3]:
(train_images,train_labels),(test_images,test_labels) = mnist.load_data()

model = keras.Sequential([layers.Dense(512,activation='relu',input_shape=(28*28,)),
                          layers.Dense(10, activation='Softmax')])

model.compile(optimizer='rmsprop', loss = 'categorical_crossentropy' , metrics=["accuracy"],)

11490434/11490434 [==============================] - 0s 0us/step


**Reshape Images and change colour range of Images between 0 to 1**

In [4]:
train_images = train_images.reshape(60000,28*28)
test_images = test_images.reshape(10000,28*28)
train_images = train_images.astype('float32')/255
test_images = test_images.astype('float32')/255
print(train_labels)

[5 0 4 ... 5 6 8]


**Apply One Hot Encoding**

In [5]:
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)
print(train_labels)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


**Training Machine Learning Model**

In [11]:
model.fit(train_images,train_labels,epochs=10,batch_size=512,callbacks=[callback],verbose=1)

Epoch 1/10
118/118 [==============================] - 1s 6ms/step - loss: 0.0794 - accuracy: 0.9773
Epoch 2/10
118/118 [==============================] - 1s 6ms/step - loss: 0.0653 - accuracy: 0.9815
Epoch 3/10
118/118 [==============================] - 1s 6ms/step - loss: 0.0544 - accuracy: 0.9846
Epoch 4/10
118/118 [==============================] - 1s 6ms/step - loss: 0.0453 - accuracy: 0.9876
Epoch 5/10
118/118 [==============================] - 1s 6ms/step - loss: 0.0383 - accuracy: 0.9896
Epoch 6/10
116/118 [============================>.] - ETA: 0s - loss: 0.0326 - accuracy: 0.9915
Desired Accuracy is Reached!!
118/118 [==============================] - 1s 6ms/step - loss: 0.0327 - accuracy: 0.9914


## Making Checkpoints

In [20]:
checkpoint_callback = ModelCheckpoint('./content/drive/MyDrive/Saved_Models/DigitClassification99.08.h5', monitor='val_accuracy', save_best_only=True, mode='max')

## Applying Training By Using Checkpoints

In [21]:
model.fit(train_images,train_labels,validation_split=0.2,epochs=10,batch_size=512,callbacks=[checkpoint_callback],verbose=1)

Epoch 1/10
94/94 [==============================] - 1s 8ms/step - loss: 0.0046 - accuracy: 0.9997 - val_loss: 0.0308 - val_accuracy: 0.9903
Epoch 2/10
94/94 [==============================] - 1s 7ms/step - loss: 0.0039 - accuracy: 0.9998 - val_loss: 0.0301 - val_accuracy: 0.9907
Epoch 3/10
94/94 [==============================] - 1s 7ms/step - loss: 0.0034 - accuracy: 0.9999 - val_loss: 0.0297 - val_accuracy: 0.9913
Epoch 4/10
94/94 [==============================] - 1s 7ms/step - loss: 0.0029 - accuracy: 0.9999 - val_loss: 0.0309 - val_accuracy: 0.9909
Epoch 5/10
94/94 [==============================] - 1s 7ms/step - loss: 0.0026 - accuracy: 1.0000 - val_loss: 0.0305 - val_accuracy: 0.9913
Epoch 6/10
94/94 [==============================] - 1s 7ms/step - loss: 0.0024 - accuracy: 1.0000 - val_loss: 0.0310 - val_accuracy: 0.9906
Epoch 7/10
94/94 [==============================] - 1s 7ms/step - loss: 0.0021 - accuracy: 1.0000 - val_loss: 0.0314 - val_accuracy: 0.9908
Epoch 8/10
94/94 [==

In [18]:
model.save('./content/drive/MyDrive/Saved_Models/DigitClassification99.08.h5')

**Evaluating Model Results**

In [22]:
test_loss,test_acc = model.evaluate(test_images,test_labels)
test_acc

313/313 [==============================] - 1s 2ms/step - loss: 0.0617 - accuracy: 0.9825


0.9825000166893005

## Making Model by Using CNN & Maxpooling

In [52]:
(train_images,train_labels),(test_images,test_labels) = mnist.load_data()

test_images = test_images.reshape(10000,28,28,1)
train_images = train_images.reshape(60000,28,28,1)
train_images = train_images.astype('float32')/255
test_images = test_images.astype('float32')/255
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

## Model Architecture

In [53]:
model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Flatten())
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(10, activation='softmax'))

In [54]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

## Training

In [57]:
model.fit(train_images,train_labels,validation_split=0.2,epochs=15,batch_size=512,callbacks=[checkpoint_callback],verbose=1)

Epoch 1/15
94/94 [==============================] - 4s 42ms/step - loss: 0.0342 - accuracy: 0.9895 - val_loss: 0.0328 - val_accuracy: 0.9901
Epoch 2/15
94/94 [==============================] - 4s 41ms/step - loss: 0.0315 - accuracy: 0.9904 - val_loss: 0.0330 - val_accuracy: 0.9905
Epoch 3/15
94/94 [==============================] - 4s 42ms/step - loss: 0.0300 - accuracy: 0.9908 - val_loss: 0.0334 - val_accuracy: 0.9906
Epoch 4/15
94/94 [==============================] - 4s 41ms/step - loss: 0.0285 - accuracy: 0.9909 - val_loss: 0.0370 - val_accuracy: 0.9897
Epoch 5/15
94/94 [==============================] - 4s 40ms/step - loss: 0.0260 - accuracy: 0.9920 - val_loss: 0.0357 - val_accuracy: 0.9912
Epoch 6/15
94/94 [==============================] - 4s 42ms/step - loss: 0.0250 - accuracy: 0.9923 - val_loss: 0.0349 - val_accuracy: 0.9913
Epoch 7/15
94/94 [==============================] - 4s 41ms/step - loss: 0.0228 - accuracy: 0.9928 - val_loss: 0.0347 - val_accuracy: 0.9912
Epoch 8/15
94

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


94/94 [==============================] - 4s 42ms/step - loss: 0.0180 - accuracy: 0.9940 - val_loss: 0.0371 - val_accuracy: 0.9905
Epoch 12/15
94/94 [==============================] - 4s 41ms/step - loss: 0.0190 - accuracy: 0.9937 - val_loss: 0.0349 - val_accuracy: 0.9913
Epoch 13/15
94/94 [==============================] - 4s 41ms/step - loss: 0.0181 - accuracy: 0.9945 - val_loss: 0.0342 - val_accuracy: 0.9915
Epoch 14/15
94/94 [==============================] - 4s 40ms/step - loss: 0.0178 - accuracy: 0.9939 - val_loss: 0.0365 - val_accuracy: 0.9918
Epoch 15/15
94/94 [==============================] - 4s 39ms/step - loss: 0.0170 - accuracy: 0.9945 - val_loss: 0.0353 - val_accuracy: 0.9915


## Testing

In [58]:
test_loss,test_acc = model.evaluate(test_images,test_labels)
test_acc

313/313 [==============================] - 1s 3ms/step - loss: 0.0229 - accuracy: 0.9929


0.992900013923645

**Predicting Test Images**

In [24]:
test_digits = test_images[:20]
prediction = model.predict(test_digits)
print(prediction[4].argmax())
test_labels[4]


1/1 [==============================] - 0s 24ms/step
4


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.], dtype=float32)

**Checking Parameters and other Details**

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 512)               401920    
                                                                 
 dense_1 (Dense)             (None, 10)                5130      
                                                                 
Total params: 407050 (1.55 MB)
Trainable params: 407050 (1.55 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


**Checking Model Result By Giving Random Image**

In [ ]:
img = image.load_img('/content/2.jpeg',target_size=(28,28),color_mode='grayscale')
img_array = np.array(image.img_to_array(img)).reshape(1,28*28)
model.predict(img_array)

**Saving Model in 'sav' Format**

In [ ]:
model.save('/content/HandWrittenObject.sav')