**Importing Packages**

In [1]:
from tensorflow.keras.datasets import mnist
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing import image
import numpy as np
import tensorflow

**CALL BACK FUNCTION**

In [2]:
class myCallbacks(tensorflow.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs={}):
    if(logs.get('accuracy') > 0.8):
      print('\nDesired Accuracy is Reached!!')
      # self.model.stop.training= True
      self.model.stop_training = True


callback = myCallbacks()

**Loading Mnist Dataset**

In [3]:
(train_images,train_labels),(test_images,test_labels) = mnist.load_data()
model = keras.Sequential([layers.Dense(512,activation='relu',input_shape=(28*28,)),layers.Dense(10, activation='Softmax')])
model.compile(optimizer='rmsprop', loss = 'categorical_crossentropy' , metrics=["accuracy"],)

11490434/11490434 [==============================] - 0s 0us/step


**Reshape Images and change colour range of Images between 0 to 1**

In [4]:
train_images = train_images.reshape(60000,28*28)
test_images = test_images.reshape(10000,28*28)
train_images = train_images.astype('float32')/255
test_images = test_images.astype('float32')/255
print(train_labels)

[5 0 4 ... 5 6 8]


**Apply One Hot Encoding**

In [5]:
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)
print(train_labels)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


**Training Machine Learning Model**

In [6]:
model.fit(train_images,train_labels,epochs=5,batch_size=512,callbacks=[callback])

Epoch 1/5
116/118 [============================>.] - ETA: 0s - loss: 0.4210 - accuracy: 0.8822
Desired Accuracy is Reached!!
118/118 [==============================] - 4s 27ms/step - loss: 0.4197 - accuracy: 0.8825


**Evaluating Model Results**

In [7]:
test_loss,test_acc = model.evaluate(test_images,test_labels)
test_acc

313/313 [==============================] - 1s 4ms/step - loss: 0.2592 - accuracy: 0.9241


0.9240999817848206

**Predicting Test Images**

In [8]:
test_digits = test_images[:20]
prediction = model.predict(test_digits)
prediction[4].argmax()
test_labels[4]


1/1 [==============================] - 0s 115ms/step


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.], dtype=float32)

**Checking Parameters and other Details**

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 512)               401920    
                                                                 
 dense_1 (Dense)             (None, 10)                5130      
                                                                 
Total params: 407050 (1.55 MB)
Trainable params: 407050 (1.55 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


**Checking Model Result By Giving Random Image**

In [ ]:
img = image.load_img('/content/2.jpeg',target_size=(28,28),color_mode='grayscale')
img_array = np.array(image.img_to_array(img)).reshape(1,28*28)
model.predict(img_array)

**Saving Model in 'sav' Format**

In [ ]:
model.save('/content/HandWrittenObject.sav')

**Reloading The Same Model**

In [ ]:
network = keras.models.load_model('/content/HandWrittenObject.sav')

In [ ]:
network.summary()

In [ ]:
network.predict(img_array)